version: 2

project_name: conservation

before:
  hooks:
    - go mod tidy

builds:
  - id: conservationd
    main: ./cmd/daemon
    binary: conservationd
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      # - arm64
  - id: conservationctl
    main: ./cmd/cli
    binary: conservationctl
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      # - arm64

archives:
  - id: conservation-archive
    ids: [conservationd, conservationctl]
    name_template: "conservation-daemon_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [ 'tar.gz']
    files: []

nfpms:
  - id: pkgs
    package_name: conservation-daemon
    file_name_template: "{{ .ConventionalFileName }}"
    formats: [deb, rpm, apk, archlinux]
    maintainer: "Marco Realacci <marco@marcorealacci.me>"
    description: "Battery conservation mode daemon for Lenovo Yoga/IdeaPad (ships conservationctl CLI)"
    license: MIT
    homepage: "https://git.marcorealacci.me/marcorealacci/conservation-daemon"
    dependencies:
      - upower
    provides:
      - conservationd
      - conservationctl
    conflicts: []
    ids:
      - conservationd
      - conservationctl
    bindir: /usr/bin
    contents:
      - src: ./packaging/systemd/conservationd.service
        dst: /usr/lib/systemd/system/conservationd.service
    scripts:
      postinstall: ./packaging/scripts/postinstall.sh
      preremove: ./packaging/scripts/preremove.sh
      postremove: ./packaging/scripts/postremove.sh

checksum:
  name_template: "checksums.txt"

changelog:
  use: git
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^chore:'

release:
  draft: false
  prerelease: auto

gitea_urls:
  api: https://git.marcorealacci.me/api/v1/
  download: https://git.marcorealacci.me/

# uploads:
#   - name: forgejo-generic-archives
#     ids: [conservation-archive]
#     target: "{{ .Env.FORGEJO_URL }}/api/packages/{{ .Env.FORGEJO_OWNER }}/generic/conservation-daemon/{{ .Version }}/{{ .ArtifactName }}"
#     method: PUT
#     custom_artifact_name: true
#     custom_headers:
#       Authorization: "token {{ .Env.FORGEJO_TOKEN }}"
#       Content-Type: application/octet-stream
#     mode: archive

aurs:
  - name: conservation-daemon-bin
    ids: [conservation-archive]
    homepage: https://git.marcorealacci.me/marcorealacci/conservation-daemon
    description: Battery conservation mode daemon for Lenovo Yoga/IdeaPad
    maintainers:
      - Marco Realacci <marco@marcorealacci.me>
    license: MIT
    provides: [conservation-daemon, conservationd, conservationctl]
    conflicts: [conservation-daemon]
    depends: [upower]
    # Fill this with your actual AUR repo when ready and set a private_key env var
    git_url: "ssh://aur@aur.archlinux.org/conservation-daemon-bin.git"
    private_key: "{{ .Env.AUR_PRIVATE_KEY }}"
    skip_upload: auto
    # Download URLs for release artifacts hosted in Forgejo Package Registry (generic)
    url_template: "https://git.marcorealacci.me/marcorealacci/conservation-daemon/releases/download/v{{ .Version }}/{{ .ArtifactName }}"
    # Package instructions: install binary and systemd unit
    package: |-
      install -Dm755 "./conservationd" "${pkgdir}/usr/bin/conservationd"
      install -Dm755 "./conservationctl" "${pkgdir}/usr/bin/conservationctl"
      # Write systemd unit file
      install -d "${pkgdir}/usr/lib/systemd/system"
      printf '%s\n' \
        '[Unit]' \
        'Description=Battery Conservation Mode Daemon (Lenovo Yoga/IdeaPad)' \
        'After=network.target dbus.service upower.service' \
        'Wants=upower.service' \
        '' \
        '[Service]' \
        'Type=simple' \
        'ExecStart=/usr/bin/conservationd' \
        'Restart=on-failure' \
        'RestartSec=5s' \
        'RuntimeDirectory=conservationd' \
        'Group=conservationd' \
        'RuntimeDirectoryMode=0770' \
        '' \
        '[Install]' \
        'WantedBy=multi-user.target' \
        > "${pkgdir}/usr/lib/systemd/system/conservationd.service"
    # Include a .install file to manage systemd
    install: ./packaging/aur/conservationd.install
