name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORGEJO_PULL_TOKEN }}
          ref: ${{ github.ref }}
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Set up Go cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install GoReleaser
        shell: bash
        run: |
          set -euo pipefail
          echo "Installing GoReleaser via go install"
          go install github.com/goreleaser/goreleaser/v2@latest
          echo "GoReleaser version:"
          $(go env GOPATH)/bin/goreleaser --version

      - name: Build and publish packages
        shell: bash
        env:
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
          AUR_PRIVATE_KEY: ${{ secrets.AUR_PRIVATE_KEY }}
          FORGEJO_URL: ${{ secrets.FORGEJO_URL }}
          FORGEJO_OWNER: ${{ secrets.FORGEJO_OWNER }}
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
        run: |
          # Full release: builds, uploads (HTTP), and AUR publish
          export GITEA_TOKEN=${{ secrets.FORGEJO_PULL_TOKEN }}
          unset GITHUB_TOKEN
          $(go env GOPATH)/bin/goreleaser release --clean --skip=announce

      # All publishing handled by GoReleaser above
